CATALOG-Historic-Records/orphaned-wells-ui

- .gcloudignore
- .github/workflows/deploy.yml
- app.yaml
- package-lock.json
- package.json
- src/App.test.tsx
- src/App.tsx
- src/assets/helperFunctions.js
- src/components/DocumentContainer/DocumentContainer.js
- src/components/Header/Header.js
- src/components/LassoSelector/LassoSelector.tsx
- src/components/NewProjectDialog/NewProjectDialog.js
- src/components/PopupModal/PopupModal.js
- src/components/ProjectsListTable/ProjectsListTable.js
- src/components/RecordsTable/RecordsTable.js
- src/components/Subheader/Subheader.js
- src/components/UploadDocumentsModal/UploadDocumentsModal.js
- src/index.tsx
- src/services/app.service.js
- src/tests/Header.test.js
- src/tests/ProjectsListTable.test.js
- src/views/LoginPage/LoginPage.js
- src/views/ProjectPage/ProjectPage.js
- src/views/ProjectsListPage/ProjectsListPage.js
- src/views/RecordPage/RecordPage.js
- add login page using google login
- add authorization headers to all api calls
- add config for gcloud deploy (for deploying to storage bucket)
> Google auth

- src/App.tsx
- src/components/ErrorBar/ErrorBar.js
- src/components/PopupModal/PopupModal.js
- src/services/app.service.js
- src/views/AdminPage/AdminPage.js
- add admin page accessible by users with role admin
- add functionality for adding users, approving users, and deleting users
> Admin page

- public/index.html
- src/App.tsx
- src/assets/processors.js
- src/components/DocumentContainer/DocumentContainer.js
- src/components/LassoSelector/LassoSelector.tsx
- src/components/LassoSelector/styles.css
- src/components/RecordsTable/RecordsTable.js
- src/components/Subheader/Subheader.js
- src/views/AdminPage/AdminPage.js
- src/views/ProjectPage/ProjectPage.js
- src/views/ProjectsListPage/ProjectsListPage.js
- src/views/RecordPage/RecordPage.js
- add trained processor as an option for projects
- update records table
- remove attributes (there are too many to be displayed as columns here)
- add status, review status, and record name
- make record names editable
- add functionality for handling subattributes in record attributes table
- make document image and record table expandable, and add confidence to expanded table
- update subheader to show and allow navigation to previous pages
> Add new processor, update records table

- src/services/app.service.js
- src/views/AdminPage/AdminPage.js
- fix admin actions
- update backend url
> Fix admin actions

- src/assets/helperFunctions.js
- src/assets/processors.js
- src/services/app.service.js
- revoke tokens upon logout
- rename old processor
> Update processor data, logout function

- package-lock.json
- package.json
- public/index.html
- src/App.tsx
- src/assets/helperFunctions.js
- src/components/DocumentContainer/DocumentContainer.js
- src/components/ImageCropper/ImageCropper.js
- src/components/ProjectsListTable/ProjectsListTable.js
- src/components/RecordsTable/RecordsTable.js
- src/services/app.service.js
- src/views/RecordPage/RecordPage.js
- add api number, confidence data to records table #14 
- remove boxy corners from highlighted attribute box in record image
- add index to records #18 
- remove edit-ability of top level attribute when there are subattributes #22 
- allow for keyboard navigation through attributes by tabbing #21 
- allow for navigation between records with arrow buttons and using arrow keys #16
> Updates from feedback 1

- src/components/RecordsTable/RecordsTable.js
- src/components/UploadDocumentsModal/UploadDocumentsModal.js
- src/tests/RecordsTable.test.js
- add a check to make sure that record is digitized before attempting to display API number
> Fix bug in records table

- src/assets/processors.js
- src/components/ColumnSelectDialog/ColumnSelectDialog.js
- src/components/RecordsTable/RecordsTable.js
- src/services/app.service.js
- src/tests/RecordsTable.test.js
- src/views/ProjectPage/ProjectPage.js
- src/views/RecordPage/RecordPage.js
- update export functionality
- add export type selection (JSON or CSV)
- add column selection
- remove default google processor from processor selection options
> Export improvements + Json export

- src/components/RecordsTable/RecordsTable.js
- add a try catch around calculating the average confidence, to handle when there are no attributes
> handle records in records table with no attributes found

- src/components/UploadDocumentsModal/UploadDocumentsModal.js
- update document uploader styling
- add warnings for file size and file type errors
- make max file size 10mb
issue #46
> Error handling for document uploader

- src/components/RecordAttributesTable/RecordAttributesTable.js
update conditional to ensure only that specific subattribute row is highlighted
> fix highlighting of sub-attribute rows

- src/components/Header/Header.js
- src/components/UploadDocumentsModal/UploadDocumentsModal.js
- src/services/app.service.js
- src/views/ProjectPage/ProjectPage.js
- src/views/RecordPage/RecordPage.js
- send email as query parameter on upload document, remove headers
- add option to upload zip files
- temporarily disable records tab
> Update upload document api; add zip file option

- src/assets/helperFunctions.js
- src/assets/processors.js
- src/components/DocumentContainer/DocumentContainer.js
- src/components/ErrorBar/ErrorBar.js
- src/components/ImageCropper/ImageCropper.js
- src/components/RecordAttributesTable/RecordAttributesTable.js
- src/components/Subheader/Subheader.js
- src/components/UploadDocumentsModal/UploadDocumentsModal.js
- src/views/ProjectPage/ProjectPage.js
- src/views/ProjectsListPage/ProjectsListPage.js
- src/views/RecordPage/RecordPage.js
- if a user tries to view a locked record, redirect them to the next record (unless they had clicked previous, then navigate them to the previous record)
- if a user tries to update a record that is now locked by another user, show error message then redirect them to records list
> Lock record handling

- src/App.tsx
- src/components/BottomBar/BottomBar.js
- src/components/Header/Header.js
- src/components/Notes/Notes.js
- src/components/RecordsTable/RecordsTable.js
- src/components/Subheader/Subheader.js
- src/services/app.service.js
- src/tests/Subheader.test.js
- src/views/LoginPage/LoginPage.js
- src/views/RecordPage/RecordPage.js
addresses issue #69 
- add notes column to table
- hide create project, upload document, and users tab from non admins
- add review status to record subheader
> Add notes to records table

- src/components/DocumentContainer/DocumentContainer.js
issue: can't highlight fields with no coordinates and thus can't edit those fields
solution: allow for highlighting of those fields; dont highlight anything in the image in those cases
> allow for highlighting of fields with no coordinates

- src/components/Subheader/Subheader.js
- src/views/ProjectPage/ProjectPage.js
- src/views/RecordPage/RecordPage.js
disable option to delete project/record for base users
> Disable delete actions for base users

- src/components/BottomBar/BottomBar.js
- src/components/RecordsTable/RecordsTable.js
- src/components/SplitButton/SplitButton.js
- src/components/Subheader/Subheader.js
- src/views/RecordPage/RecordPage.js
- in addition to unreviewed and reviewed, add options to mark record as incomplete or defected
> Add additional review status handling

- src/components/Notes/Notes.js
- src/components/PopupModal/PopupModal.js
- src/components/RecordsTable/RecordsTable.js
- src/views/ProjectPage/ProjectPage.js
- only show notes icon as colored if there are notes present
> Notes icon coloring

- src/assets/processors.js
- update attributes for version a; update names to match gcp
> Update ISGS processor version A schema

- src/assets/processors.js
- src/components/NewProjectDialog/NewProjectDialog.js
- update schema for isgs processor version a
> merge main into isgs

- src/components/DocumentContainer/DocumentContainer.js
- src/components/ImageCropper/ImageCropper.js
- src/views/RecordPage/RecordPage.js
- instantiate an imagewrapper for each image rather than just one
- update scroll function to handle scrolling to different pages
> Handle records with mulitple images

- src/components/DocumentContainer/DocumentContainer.js
- increase top offset from 50px to 100px
> Ensure highlighted text in image isn't cutoff

- src/components/Header/Header.css
- src/components/Subheader/Subheader.js
make overflow auto instead of scroll for header and subheader
> Fix phantom scroll bars on windows

- package-lock.json
- package.json
- src/assets/filterOptions.js
- src/components/RecordsTable/RecordsTable.js
- src/components/TableFilters/TableFilters.js
- src/services/app.service.js
- src/views/ProjectPage/ProjectPage.js
issue #39 
- add pagination
- add filtering by name, date, review status
- add sorting on select columns
> Pagination, filtering, sorting on project/records view

- src/assets/helperFunctions.js
- src/components/RecordsTable/RecordsTable.js
- src/components/TableFilters/TableFilters.js
- src/tests/RecordsTable.test.js
- src/views/ProjectPage/ProjectPage.js
when filters are set on the project page (list of records), save these so they persist
> Make filtering persistent on project page

- src/App.tsx
- src/components/Header/Header.tsx
- src/index.tsx
- src/types.ts
- src/usercontext.tsx
- src/views/RecordPage/RecordPage.tsx
- use this for storing user information to use throughout the app
> Add user context

- src/components/ColumnSelectDialog/ColumnSelectDialog.tsx
- src/components/ProjectsListTable/ProjectsListTable.tsx
- src/components/RecordsTable/RecordsTable.tsx
- src/tests/mockProjects.json
- src/types.ts
- src/views/ProjectPage/ProjectPage.tsx
projectdata[id_] -> projectdata[_id]
> Fix project id naming consistency

- .github/workflows/tests.yml
- src/views/RecordPage/RecordPage.tsx
- src/views/TeamRecordsPage/TeamRecordsPage.tsx
> fix review status updating

- src/components/ColumnSelectDialog/ColumnSelectDialog.tsx
- src/components/RecordsTable/RecordsTable.tsx
- src/services/app.service.ts
- src/types.ts
- include filter, sort in columnselect download records
- relies on [server pr 95](https://github.com/CATALOG-Historic-Records/orphaned-wells-ui-server/pull/95)
> Apply filters when exporting records

- src/components/ColumnSelectDialog/ColumnSelectDialog.tsx
- src/components/RecordNotesDialog/RecordNotesDialog.tsx
- ensure deleted comments dont display (lil bug from the last PR)
- improve styling of dialog
> Clean up new notes dialog

- cypress/e2e/spec.cy.js
- src/components/ColumnSelectDialog/ColumnSelectDialog.tsx
- src/services/app.service.ts
- src/tests/mockProjects.json
- src/types.ts
- add option to download document images in addition to csv, json
- relies on [server pr 100](https://github.com/CATALOG-Historic-Records/orphaned-wells-ui-server/pull/100)
> Download document images

- src/assets/util.ts
- src/components/ColumnSelectDialog/ColumnSelectDialog.tsx
- src/components/Header/Header.tsx
- src/components/RecordNotesDialog/RecordNotesDialog.tsx
- when changing teams, navigate to homepage
- clean up api call code
> Some cleanup

- cypress/e2e/spec.cy.js
- src/assets/styles.ts
- src/assets/util.ts
- src/components/DocumentContainer/DocumentContainer.tsx
- src/components/RecordAttributesTable/RecordAttributesTable.tsx
- src/components/RecordsTable/RecordsTable.tsx
- src/types.ts
- src/views/RecordPage/RecordPage.tsx
- fix test
- update error styling
-
> Cleaning functions rd 2

- src/assets/styles.ts
- src/components/DocumentContainer/DocumentContainer.tsx
- src/components/RecordAttributesTable/RecordAttributesTable.tsx
- only show "Edited value: " when that field was edited 
- add error banner on record page
> cleaning functions pt 3

- public/index.html
- remove broken script from index.html (it was seriously slowing things down)
> remove broken script tag

- public/index.html
- public/styles/react-crop.css
- remove react crop cdns, copy css locally (this thing has randomly given issues a couple times)
> Replace react-crop cdns in index.html

- .github/workflows/deploy.yml
- cypress/e2e/spec.cy.js
- package.json
- src/components/NewProjectDialog/NewProjectDialog.tsx
- src/components/NewRecordGroupDialog/NewRecordGroupDialog.tsx
- src/components/RecordAttributesTable/RecordAttributesTable.tsx
> Make subfield tables open by default; navigate to project, record group upon creation

- src/components/RecordAttributesTable/RecordAttributesTable.tsx
- src/components/RecordGroupsTable/RecordGroupsTable.tsx
- src/components/RecordsTable/RecordsTable.tsx
- src/views/ProjectPage/ProjectPage.tsx
- for progress, sort by unreviewed amount
> Make record groups table sortable

- src/components/RecordAttributesTable/RecordAttributesTable.tsx
- src/types.ts
- src/views/RecordPage/RecordPage.tsx
relies on [server pr 123](https://github.com/CATALOG-Historic-Records/orphaned-wells-ui-server/pull/123)
- fix review status updating
> Add new fields pt 2

- src/components/ColumnSelectDialog/ColumnSelectDialog.tsx
- src/components/DocumentContainer/DocumentContainer.tsx
- src/components/ImageCropper/ImageCropper.tsx
- src/components/RecordAttributesTable/RecordAttributesTable.tsx
- src/styles.ts
- src/types.ts
- src/util.ts
- src/views/RecordPage/RecordPage.tsx
- Combine attributes subattributes tables
- add select all button for column select
- dont allow options to overlap in column select
- clean up scrolling functionality
> Improve scrolling, clean column select options, add select all
